settings:
  volume_step: 2.0
  logging: False

channels:
  desktop: 5

hotkeys:
  desktop:
    mute: 
      - "ctrl+f13"
      - "f16"
    up:
      - "ctrl+f14"
      - "f18"
    down:
      - "ctrl+f15"
      - "f17"
